// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _2025_employment_1.Data;

#nullable disable

namespace _2025_employment_1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251119071759_AddConversationLogs")]
    partial class AddConversationLogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("_2025_employment_1.Models.ConversationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("FaceMemoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FaceMemoId");

                    b.ToTable("ConversationLogs");
                });

            modelBuilder.Entity("_2025_employment_1.Models.FaceMemo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Affiliation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FaceDescriptorJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FaceMemos");
                });

            modelBuilder.Entity("_2025_employment_1.Models.ConversationLog", b =>
                {
                    b.HasOne("_2025_employment_1.Models.FaceMemo", "FaceMemo")
                        .WithMany("ConversationLogs")
                        .HasForeignKey("FaceMemoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FaceMemo");
                });

            modelBuilder.Entity("_2025_employment_1.Models.FaceMemo", b =>
                {
                    b.Navigation("ConversationLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
