// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _2025_employment_1.Data;

#nullable disable

namespace _2025_employment_1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251203090214_Changeuuid")]
    partial class Changeuuid
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("_2025_employment_1.Models.ConversationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("FaceMemoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FaceMemoId");

                    b.ToTable("ConversationLogs");
                });

            modelBuilder.Entity("_2025_employment_1.Models.FaceMemo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Affiliation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FaceDescriptorJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("SocialMediaHandle")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("FaceMemos");
                });

            modelBuilder.Entity("_2025_employment_1.Models.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Organizations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d8591a27-6350-4d4f-9818-701385055051"),
                            Name = "本社開発部"
                        },
                        new
                        {
                            Id = new Guid("2656f481-2b7e-46bb-b778-433555207212"),
                            Name = "大阪支店"
                        },
                        new
                        {
                            Id = new Guid("a0f3d4c4-7230-4596-a447-735952331584"),
                            Name = "東京営業所"
                        },
                        new
                        {
                            Id = new Guid("e198084e-2868-4503-b0e6-990747424422"),
                            Name = "名古屋センター"
                        },
                        new
                        {
                            Id = new Guid("83907106-e752-4a00-9833-286c0716c514"),
                            Name = "福岡ラボ"
                        },
                        new
                        {
                            Id = new Guid("c3182512-8806-444a-953e-5d15c8172901"),
                            Name = "札幌サテライト"
                        },
                        new
                        {
                            Id = new Guid("f5e1b2a9-0d8c-4e6f-924b-3d7a8b5c9e0d"),
                            Name = "海外事業部"
                        },
                        new
                        {
                            Id = new Guid("9d7f6c3a-1b2e-48a5-bc9d-4e5f6a7b8c9d"),
                            Name = "品質管理課"
                        },
                        new
                        {
                            Id = new Guid("b2a4c6d8-9e0f-41a3-8c5d-7b9e0f2a4c6d"),
                            Name = "人事総務部"
                        },
                        new
                        {
                            Id = new Guid("4e6f8a0b-2c4d-6e8f-0a2b-4c6d8e0f2a4b"),
                            Name = "第2開発室"
                        });
                });

            modelBuilder.Entity("_2025_employment_1.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("_2025_employment_1.Models.ConversationLog", b =>
                {
                    b.HasOne("_2025_employment_1.Models.FaceMemo", "FaceMemo")
                        .WithMany("ConversationLogs")
                        .HasForeignKey("FaceMemoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FaceMemo");
                });

            modelBuilder.Entity("_2025_employment_1.Models.FaceMemo", b =>
                {
                    b.HasOne("_2025_employment_1.Models.Organization", "Organization")
                        .WithMany("FaceMemos")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("_2025_employment_1.Models.User", b =>
                {
                    b.HasOne("_2025_employment_1.Models.Organization", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationId");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("_2025_employment_1.Models.FaceMemo", b =>
                {
                    b.Navigation("ConversationLogs");
                });

            modelBuilder.Entity("_2025_employment_1.Models.Organization", b =>
                {
                    b.Navigation("FaceMemos");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
